### ISSUE TITLE
The name 'Pi' does not exist in the current context

### ISSUE THREAD

**Issue by mikmas** [unosquare/wiringpi-dotnet#31]
I tried to use your example:
    // All 3 methods below are exactly equivalent
    var blinkingPin = Pi.Gpio[17];
    blinkingPin = Pi.Gpio[BcmPin.Gpio17];
    blinkingPin = Pi.Gpio.Pin17;
There is only Unosquare.WiringPi namespace, which does not have "Pi" class

**Comment by geoperez** [comment]
You need to add RaspberryIO Nuget too (https://github.com/unosquare/raspberryio)
